# Generated by Django 6.1 on 2026-08-11 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentrecord',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('CASH', 'Cash'), ('DIGITAL', 'Digital (UPI/Bank)')], max_length=10, null=True),
        ),
    ]
