# Generated by Django 6.1 on 2026-08-11 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0002_rentrecord_payment_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(choices=[('MAINTENANCE', 'Maintenance / मरम्मत'), ('WATER', 'Water Bill / पानी'), ('ELECTRICITY', 'Electricity (Common) / बिजली'), ('CLEANING', 'Cleaning / सफाई'), ('REPAIR', 'Repairs / मरम्मत'), ('TAX', 'Tax / Society'), ('OTHER', 'Other / अन्य')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('DIGITAL', 'Digital (UPI/Bank)')], default='CASH', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rental.property')),
            ],
        ),
    ]
