# Generated by Django 6.1 on 2026-08-11 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0003_expense'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentrecord',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='rentrecord',
            name='status',
            field=models.CharField(choices=[('PAID', 'Paid'), ('PARTIAL', 'Partial'), ('PENDING', 'Pending')], default='PENDING', max_length=10),
        ),
    ]
