# Generated by Django 6.1 on 2026-08-13 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0004_rentrecord_amount_paid_alter_rentrecord_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('DIGITAL', 'Digital (UPI/Bank)')], max_length=10)),
                ('payment_date', models.DateField()),
                ('note', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rent_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='rental.rentrecord')),
            ],
        ),
    ]
