# Generated by Django 6.1 on 2026-08-14 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0006_alter_payment_options_tenant_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('AADHAAR', 'Aadhaar Card'), ('AGREEMENT', 'Rent Agreement'), ('PHOTO', 'Photo'), ('POLICE', 'Police Verification'), ('OTHER', 'Other')], max_length=20)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('file', models.FileField(upload_to='tenant_documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='rental.tenant')),
            ],
        ),
    ]
