# Generated by Django 6.1 on 2026-08-14 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0007_tenantdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='billing_day',
            field=models.PositiveSmallIntegerField(default=1, help_text='Day of the month when rent cycle starts (1-28)'),
        ),
    ]
